language: php
sudo: false

php:
  - '7.1'

env:
  - SYMFONY_VERSION="3.0.*" DB=mysql
  - NOTIFICATION_SERVER=http://localhost:8000
  - NOTIFICATION_TOKEN=

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - bash -c "git clone https://github.com/Wolnosciowiec/wolnosciowiec-notification /tmp/notification"
  - cd /tmp/notification && composer self-update
  - cd /tmp/notification && cp app/config/notification.yml.dist app/config/notification.yml
  - cd /tmp/notification && cp app/config/parameters.yml.dist app/config/parameters.yml
  - cd /tmp/notification && composer install
  - cd /tmp/notification && php bin/console server:start

script:
  - ./test/run-tests.sh
